version: '3'
services:
  couchdb:
    image: couchdb:3.5
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - "5984:5984"
    volumes:
      - ./wait-for-couchdb.sh:/docker-entrypoint-initdb.d/init.sh